# infra/docker/docker-compose.yml
version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin # Use secrets!
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data

  postgres_db: # New service for PostgreSQL
    image: postgres:15 # Use a specific version
    container_name: taskapp_postgres # Optional: specific container name
    environment:
      POSTGRES_DB: task_db          # Database name
      POSTGRES_USER: task_user      # Database user
      POSTGRES_PASSWORD: task_password # CHANGE THIS - Use secrets!
    ports:
      - "5432:5432" # Map host port 5432 to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database data

volumes:
  keycloak_data:
  postgres_data: # Define the volume for postgres